Summarise group by
uoc-data-science/r_python pull request #3
Opened 2019-05-09 09:06 UTC by romantilly

2019-05-09 09:28 UTC, NicoLdrt requested changes

2019-05-09 09:28 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Purpose:
```suggestion
Purpose: Create one or more scalar variables summarizing the variables of an existing table. Tables with groups created by 'group_by()' will result in one row in the output for each group. Tables with no groups will result in one row.<br>
```

2019-05-09 09:28 UTC, NicoLdrt commented on r_py_cheatsheet.md
>  1. ...
```suggestion
1. https://dplyr.tidyverse.org/reference/summarise.html
```

2019-05-09 09:28 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Official documentation: https://dplyr.tidyverse.org/reference/summarise.html
Ist nicht die offizielle Dokumentation
```suggestion
Official documentation: https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/summarise
```

2019-05-09 09:28 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Official documentation: https://dplyr.tidyverse.org/reference/summarise.html
+ Line Break ist einfach schöner
```suggestion
Official documentation: https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/summarise<br>
```

2019-05-09 18:04 UTC, JBraun253 approved these changes
Looks good.

2019-05-10 17:38 UTC, NicoLdrt approved these changes

2019-05-10 17:38 UTC, merged