Mutate
uoc-data-science/r_python pull request #4
Opened 2019-05-09 09:07 UTC by phyk

Mutate Python and R

2019-05-09 09:41 UTC, LaurenzH commented
working

2019-05-09 09:41 UTC, LaurenzH approved these changes
working

2019-05-09 18:43 UTC, Marcuard requested changes

2019-05-09 18:43 UTC, Marcuard commented on r_py_cheatsheet.md
> +mtcars.assign(displ_l = mtcars["disp"] / 61.0237)
```suggestion
mtcars = mtcars.assign(displ_l = mtcars["disp"] / 61.0237)
```
Just to be able to see the result when printing.

2019-05-10 10:17 UTC, Marcuard approved these changes

2019-05-10 16:08 UTC, merged