Arrange
uoc-data-science/r_python pull request #5
Opened 2019-05-09 09:07 UTC by Marcuard

2019-05-09 09:19 UTC, NicoLdrt requested changes
Purpose ausformuliert und Formatierungsänderungen

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +iris = read.csv("iris.csv")
Hier sollten weitere Links zu Tutorials hin, der Code in den dafür vorgesehenen ``` Block

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Purpose: Unordered observations. Arrange reorders observations.
```suggestion
Purpose: Unordered observations. Arrange reorders observations.<br>
```

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Official documentation: https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/arrange
```suggestion
Official documentation: https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/arrange<br>
```

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
Hierhin der Code

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Purpose: Unordered observations. Arrange reorders observations.
+ Könnte ein ganzer Satz sein, dann wäre es bisschen verständlicher.
```suggestion
Purpose: When you have unordered observations, 'arrange' can reorder observations and improve the structure of the dataset.<br>
```

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +import pandas as pd
siehe oben

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Purpose: Unordered observations. Arrange reorders observations.
```suggestion
Purpose: Unordered observations. Arrange reorders observations.<br>
```

2019-05-09 09:19 UTC, NicoLdrt commented on r_py_cheatsheet.md
> +Documentation: http://pandas.pydata.org/pandas-docs/version/0.19/generated/pandas.DataFrame.sort.html
```suggestion
Documentation: http://pandas.pydata.org/pandas-docs/version/0.19/generated/pandas.DataFrame.sort.html<br>
```

2019-05-09 09:26 UTC, phyk requested changes
Changes in formatting

2019-05-09 09:26 UTC, phyk commented on r_py_cheatsheet.md
> +iris = read.csv("iris.csv")
```suggestion
```

2019-05-09 09:26 UTC, phyk commented on r_py_cheatsheet.md
```suggestion
```
iris = read.csv("iris.csv")
iris_sorted = arrange(iris, sepal.length)
iris_sorted2 = arrange(iris, desc(sepal.length), sepal.width)
```
```

2019-05-09 09:26 UTC, phyk commented on r_py_cheatsheet.md
> +1. iris_sorted = arrange(iris, sepal.length)
```suggestion
```

2019-05-09 09:26 UTC, phyk commented on r_py_cheatsheet.md
> +2. iris_sorted2 = arrange(iris, desc(sepal.length), sepal.width)
```suggestion

```

2019-05-09 09:26 UTC, phyk commented on r_py_cheatsheet.md
```
import pandas as pd
path ="./iris.csv"
df = pd.read_csv(path, sep=";")
df = df.sort_values(by=['Sepal.Length'], ascending=[True])
df = df.sort_values(by=['Sepal.Length', 'Sepal.Width'], ascending=[True, False])
df = df.sort_values(by=['Sepal.Length', 'Sepal.Width'], ascending=[True, False], na_position= 'first')
```

2019-05-09 19:12 UTC, Marcuard commented
Updated R and Python sections.

2019-05-10 08:07 UTC, phyk approved these changes

2019-05-10 17:39 UTC, NicoLdrt approved these changes

2019-05-10 18:02 UTC, merged